In [1]:
import pandas as pd

In [15]:
df = pd.read_csv('badges_contre_gambie_date.csv')
df.head()

,number,prenom,nom,telephone,structure,type,nb impression,date impression,date
0,9927451456,Ibrahima,DIALLO,772924308,RTS,JOURNALISTE,0.0,NaN,2026-03-09 15:09:52.274818
1,6455075325,Anoir,Ibniyamine,778574387,Diotali,JOURNALISTE,7.0,2026-03-11 10:03:13.528100,2026-03-10 18:17:25.065881
2,8266310798,CHEIKH BAMBA,DIAGNE,773167827,CHALLENGESPORTS.INFO,JOURNALISTE,1.0,2026-03-25 13:18:09.808642,2026-03-11 00:27:06.478566
3,5498628538,Benoit,BADIANE,775466755,RTS,JOURNALISTE,1.0,2026-03-25 13:18:29.659722,2026-03-11 13:09:09.745459
4,4333177119,Ben Abass,Faye,777016538,RECORD,JOURNALISTE,1.0,2026-03-25 13:19:14.844196,2026-03-11 14:13:53.205106

In [10]:
df.shape

(1357, 9)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1357 entries, 0 to 1356
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   number           1357 non-null   int64
 1   prenom           1108 non-null   object
 2   nom              1107 non-null   object
 3   telephone        1074 non-null   object
 4   structure        1356 non-null   object
 5   type             1357 non-null   object
 6   nb impression    1356 non-null   float64
 7   date impression  1097 non-null   object
 8   date             1357 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 95.5+ KB

In [16]:
df = df[["nb impression", "structure", "type", "date"]]
df.head()

,nb impression,structure,type,date
0,0.0,RTS,JOURNALISTE,2026-03-09 15:09:52.274818
1,7.0,Diotali,JOURNALISTE,2026-03-10 18:17:25.065881
2,1.0,CHALLENGESPORTS.INFO,JOURNALISTE,2026-03-11 00:27:06.478566
3,1.0,RTS,JOURNALISTE,2026-03-11 13:09:09.745459
4,1.0,RECORD,JOURNALISTE,2026-03-11 14:13:53.205106

In [17]:
df = df.iloc[2:]
df.head()

,nb impression,structure,type,date
2,1.0,CHALLENGESPORTS.INFO,JOURNALISTE,2026-03-11 00:27:06.478566
3,1.0,RTS,JOURNALISTE,2026-03-11 13:09:09.745459
4,1.0,RECORD,JOURNALISTE,2026-03-11 14:13:53.205106
5,1.0,Jolofsport.com,JOURNALISTE,2026-03-11 14:19:15.949357
6,1.0,Taggat,JOURNALISTE,2026-03-11 14:23:13.165933

In [19]:
df["date"] = pd.to_datetime(df["date"])
df.head()

   nb impression             structure         type                       date
2            1.0  CHALLENGESPORTS.INFO  JOURNALISTE 2026-03-11 00:27:06.478566
3            1.0                   RTS  JOURNALISTE 2026-03-11 13:09:09.745459
4            1.0                RECORD  JOURNALISTE 2026-03-11 14:13:53.205106
5            1.0        Jolofsport.com  JOURNALISTE 2026-03-11 14:19:15.949357
6            1.0                Taggat  JOURNALISTE 2026-03-11 14:23:13.165933

In [20]:
df['date'] = pd.to_datetime(df['date']).dt.date
df.head()

   nb impression             structure         type        date
2            1.0  CHALLENGESPORTS.INFO  JOURNALISTE  2026-03-11
3            1.0                   RTS  JOURNALISTE  2026-03-11
4            1.0                RECORD  JOURNALISTE  2026-03-11
5            1.0        Jolofsport.com  JOURNALISTE  2026-03-11
6            1.0                Taggat  JOURNALISTE  2026-03-11

In [ ]:
df["type"].value_counts()

type
PHOTOGRAPHE                               259
JOURNALISTE                               176
COMMISSION ORGANISATION                   146
COMMISSION MARKETING                       88
SOGIP                                      84
EQUIPE NATIONALE DU SENEGAL                52
EQUIPE NATIONALE GAMBIE                    50
JOURNALISTE GAMBIE                         48
COMMISSION SECURITE                        47
SPONSOR                                    45
HOSPITALITE                                44
COMMISSION MEDICALE                        42
COMMISSION COMMUNICATION                   33
COJOJ                                      29
COMITE EXECUTIF                            24
POLICE                                     24
ADMINISTRATION FEDERALE                    23
COMMISSION PROTOCOLE                       23
MINISTERE DE LA JEUNESSE ET DES SPORTS     20
CHAUFFEUR                                  20
COMMISSION CCATP                           17
CONCESSION                                 14
OFFICIEL CAF                               13
COMMISSION MOBILISATION                     8
PRESIDENT LIGUE REGIONALE                   5
COMMISSION FINANCES                         5
SENELEC                                     5
COMMISSION ETHIQUE FAIR-PLAY                4
COMMISSION AUDIT                            2
RTS                                         1
PRESIDENT FSF                               1
COORDONNATEUR GENERAL                       1
PAVOISEMENT                                 1
PARTENAIRE FSF                              1
Name: count, dtype: int64

In [22]:
df["structure"].value_counts()

structure
FSF                        155
SOGIP                       82
HOSPITALITE                 42
SECURITE                    35
Commission Médicale         32
                          ...
Planète sport 221            1
Les Échos/ Jotaay.net        1
Aladji malick tv sport       1
FD MEDIA                     1
Ceremonies                   1
Name: count, Length: 453, dtype: int64

In [42]:
df2 = pd.read_excel('resumer.xlsx')
df2.head()

                TYPE DE BADGES  NOMBRE  IMPRIMES  DELIVRES  STADE  NB_EXACT
0  EQUIPE NATIONALE DU SENEGAL      50        50        50   15.0        65
1      EQUIPE NATIONALE GAMBIE      50        50        50    NaN        50
2                 OFFICIEL CAF      13        13        13    NaN        13
3                PRESIDENT FSF       1         1         1    NaN         1
4        COORDONNATEUR GENERAL       1         1         1    NaN         1

In [43]:
df2 = df2[["TYPE DE BADGES", "NB_EXACT"]]
df2.head()

                TYPE DE BADGES  NB_EXACT
0  EQUIPE NATIONALE DU SENEGAL        65
1      EQUIPE NATIONALE GAMBIE        50
2                 OFFICIEL CAF        13
3                PRESIDENT FSF         1
4        COORDONNATEUR GENERAL         1

In [44]:
df2.rename(columns={"TYPE DE BADGES": "type", "NB_EXACT": "nb"}, inplace=True)
df2.head()

                          type  nb
0  EQUIPE NATIONALE DU SENEGAL  65
1      EQUIPE NATIONALE GAMBIE  50
2                 OFFICIEL CAF  13
3                PRESIDENT FSF   1
4        COORDONNATEUR GENERAL   1

In [34]:
df.rename(columns={"nb impression": "nb"}, inplace=True)
df.head()

    nb             structure         type        date
2  1.0  CHALLENGESPORTS.INFO  JOURNALISTE  2026-03-11
3  1.0                   RTS  JOURNALISTE  2026-03-11
4  1.0                RECORD  JOURNALISTE  2026-03-11
5  1.0        Jolofsport.com  JOURNALISTE  2026-03-11
6  1.0                Taggat  JOURNALISTE  2026-03-11

In [45]:
types_manquants = df2[~df2["type"].isin(df["type"])]
print(types_manquants)

              type   nb
29  POLICE GAMBIE     4
30        TRAITEUR    5
32           SETER    7
33         ARTISTE  130

In [36]:
df["type"].unique()

array(['JOURNALISTE', 'PHOTOGRAPHE',
       'MINISTERE DE LA JEUNESSE ET DES SPORTS', 'COMITE EXECUTIF',
       'PRESIDENT LIGUE REGIONALE', 'ADMINISTRATION FEDERALE',
       'EQUIPE NATIONALE DU SENEGAL', 'EQUIPE NATIONALE GAMBIE', 'SOGIP',
       'OFFICIEL CAF', 'COMMISSION ETHIQUE FAIR-PLAY',
       'COMMISSION COMMUNICATION', 'HOSPITALITE', 'COMMISSION MARKETING',
       'COMMISSION MEDICALE', 'RTS', 'COMMISSION ORGANISATION',
       'COMMISSION PROTOCOLE', 'COMMISSION SECURITE', 'SENELEC',
       'SPONSOR', 'PAVOISEMENT', 'COJOJ', 'COORDONNATEUR GENERAL',
       'PRESIDENT FSF', 'COMMISSION CCATP', 'JOURNALISTE GAMBIE',
       'COMMISSION FINANCES', 'COMMISSION AUDIT',
       'COMMISSION MOBILISATION', 'POLICE', 'CHAUFFEUR', 'CONCESSION',
       'PARTENAIRE FSF'], dtype=object)

In [41]:
types_manquants = df[~df["type"].isin(df2["type"])]
types_manquants

       nb        structure             type        date
457   0.0  Comité Exécutif  COMITE EXECUTIF  2026-03-23
458   1.0  Comité Exécutif  COMITE EXECUTIF  2026-03-23
459   1.0  Comité Exécutif  COMITE EXECUTIF  2026-03-23
460   1.0  Comité Exécutif  COMITE EXECUTIF  2026-03-23
461   2.0  Comité Exécutif  COMITE EXECUTIF  2026-03-23
...   ...              ...              ...         ...
1338  0.0              FSF        CHAUFFEUR  2026-03-27
1339  0.0              FSF        CHAUFFEUR  2026-03-27
1340  0.0              FSF        CHAUFFEUR  2026-03-27
1341  1.0              FSF        CHAUFFEUR  2026-03-27
1356  1.0              FSF   PARTENAIRE FSF  2026-03-30

[141 rows x 4 columns]

In [46]:
df = df.merge(df2[["type", "nb"]], on="type", how="left", suffixes=("", "_df2"))

df["nb"] = df.groupby("type")["nb_df2"].transform(
    lambda x: [x.iloc[0]] + [0]*(len(x)-1)
)

df = df.drop(columns=["nb_df2"])
df.head()

      nb             structure         type        date
0  169.0  CHALLENGESPORTS.INFO  JOURNALISTE  2026-03-11
1    0.0                   RTS  JOURNALISTE  2026-03-11
2    0.0                RECORD  JOURNALISTE  2026-03-11
3    0.0        Jolofsport.com  JOURNALISTE  2026-03-11
4    0.0                Taggat  JOURNALISTE  2026-03-11

In [48]:
types_absents = set(df2["type"]) - set(df["type"])
lignes_a_ajouter = df2[df2["type"].isin(types_absents)].copy()
lignes_a_ajouter["structure"] = lignes_a_ajouter["type"]
lignes_a_ajouter["date"] = None   # ou pd.NaT si tu préfères
lignes_a_ajouter = lignes_a_ajouter[["nb", "structure", "type", "date"]]
df = pd.concat([df, lignes_a_ajouter], ignore_index=True)
df.head()

      nb             structure         type        date
0  169.0  CHALLENGESPORTS.INFO  JOURNALISTE  2026-03-11
1    0.0                   RTS  JOURNALISTE  2026-03-11
2    0.0                RECORD  JOURNALISTE  2026-03-11
3    0.0        Jolofsport.com  JOURNALISTE  2026-03-11
4    0.0                Taggat  JOURNALISTE  2026-03-11

In [49]:
types_manquants = df2[~df2["type"].isin(df["type"])]
print(types_manquants)

Empty DataFrame
Columns: [type, nb]
Index: []

In [54]:
df["type"].unique()

array(['JOURNALISTE', 'PHOTOGRAPHE',
       'MINISTERE DE LA JEUNESSE ET DES SPORTS', 'COMITE EXECUTIF',
       'PRESIDENT LIGUE REGIONALE', 'ADMINISTRATION FEDERALE',
       'EQUIPE NATIONALE DU SENEGAL', 'EQUIPE NATIONALE GAMBIE', 'SOGIP',
       'OFFICIEL CAF', 'COMMISSION ETHIQUE FAIR-PLAY',
       'COMMISSION COMMUNICATION', 'HOSPITALITE', 'COMMISSION MARKETING',
       'COMMISSION MEDICALE', 'RTS', 'COMMISSION ORGANISATION',
       'COMMISSION PROTOCOLE', 'COMMISSION SECURITE', 'SENELEC',
       'SPONSOR', 'PAVOISEMENT', 'COJOJ', 'COORDONNATEUR GENERAL',
       'PRESIDENT FSF', 'COMMISSION CCATP', 'JOURNALISTE GAMBIE',
       'COMMISSION FINANCES', 'COMMISSION AUDIT',
       'COMMISSION MOBILISATION', 'POLICE', 'CHAUFFEUR', 'CONCESSION',
       'PARTENAIRE FSF', 'POLICE GAMBIE ', 'TRAITEUR', 'SETER', 'ARTISTE'],
      dtype=object)

In [51]:
df["type"].value_counts()

type
PHOTOGRAPHE                               259
JOURNALISTE                               176
COMMISSION ORGANISATION                   146
COMMISSION MARKETING                       88
SOGIP                                      84
EQUIPE NATIONALE DU SENEGAL                52
EQUIPE NATIONALE GAMBIE                    50
JOURNALISTE GAMBIE                         48
COMMISSION SECURITE                        47
SPONSOR                                    45
HOSPITALITE                                44
COMMISSION MEDICALE                        42
COMMISSION COMMUNICATION                   33
COJOJ                                      29
POLICE                                     24
COMITE EXECUTIF                            24
ADMINISTRATION FEDERALE                    23
COMMISSION PROTOCOLE                       23
CHAUFFEUR                                  20
MINISTERE DE LA JEUNESSE ET DES SPORTS     20
COMMISSION CCATP                           17
CONCESSION                                 14
OFFICIEL CAF                               13
COMMISSION MOBILISATION                     8
PRESIDENT LIGUE REGIONALE                   5
SENELEC                                     5
COMMISSION FINANCES                         5
COMMISSION ETHIQUE FAIR-PLAY                4
COMMISSION AUDIT                            2
RTS                                         1
PAVOISEMENT                                 1
PRESIDENT FSF                               1
COORDONNATEUR GENERAL                       1
PARTENAIRE FSF                              1
POLICE GAMBIE                               1
TRAITEUR                                    1
SETER                                       1
ARTISTE                                     1
Name: count, dtype: int64

In [56]:
groupe = df.groupby("type")["nb"].sum().sort_values(ascending=False)
groupe

type
PHOTOGRAPHE                               264.0
JOURNALISTE                               169.0
ARTISTE                                   130.0
COMMISSION ORGANISATION                   102.0
SOGIP                                      78.0
EQUIPE NATIONALE DU SENEGAL                65.0
RTS                                        61.0
JOURNALISTE GAMBIE                         57.0
EQUIPE NATIONALE GAMBIE                    50.0
COMMISSION SECURITE                        47.0
SPONSOR                                    45.0
HOSPITALITE                                42.0
COMMISSION MEDICALE                        42.0
POLICE                                     38.0
COMMISSION CCATP                           37.0
COMMISSION COMMUNICATION                   32.0
COJOJ                                      28.0
COMITE EXECUTIF                            23.0
COMMISSION PROTOCOLE                       23.0
ADMINISTRATION FEDERALE                    21.0
MINISTERE DE LA JEUNESSE ET DES SPORTS     20.0
COMMISSION MARKETING                       19.0
CONCESSION                                 14.0
OFFICIEL CAF                               13.0
SETER                                       7.0
PRESIDENT LIGUE REGIONALE                   5.0
SENELEC                                     5.0
COMMISSION FINANCES                         5.0
TRAITEUR                                    5.0
POLICE GAMBIE                               4.0
COMMISSION ETHIQUE FAIR-PLAY                4.0
COMMISSION AUDIT                            2.0
PRESIDENT FSF                               1.0
COORDONNATEUR GENERAL                       1.0
PAVOISEMENT                                 1.0
CHAUFFEUR                                   0.0
COMMISSION MOBILISATION                     0.0
PARTENAIRE FSF                              0.0
Name: nb, dtype: float64

In [57]:
nb_seter = df.loc[df["type"] == "SETER", "nb"].sum()
df.loc[df["type"] == "COMMISSION ORGANISATION", "nb"] += nb_seter
df = df[df["type"] != "SETER"]

In [58]:
df["type"].unique()

array(['JOURNALISTE', 'PHOTOGRAPHE',
       'MINISTERE DE LA JEUNESSE ET DES SPORTS', 'COMITE EXECUTIF',
       'PRESIDENT LIGUE REGIONALE', 'ADMINISTRATION FEDERALE',
       'EQUIPE NATIONALE DU SENEGAL', 'EQUIPE NATIONALE GAMBIE', 'SOGIP',
       'OFFICIEL CAF', 'COMMISSION ETHIQUE FAIR-PLAY',
       'COMMISSION COMMUNICATION', 'HOSPITALITE', 'COMMISSION MARKETING',
       'COMMISSION MEDICALE', 'RTS', 'COMMISSION ORGANISATION',
       'COMMISSION PROTOCOLE', 'COMMISSION SECURITE', 'SENELEC',
       'SPONSOR', 'PAVOISEMENT', 'COJOJ', 'COORDONNATEUR GENERAL',
       'PRESIDENT FSF', 'COMMISSION CCATP', 'JOURNALISTE GAMBIE',
       'COMMISSION FINANCES', 'COMMISSION AUDIT',
       'COMMISSION MOBILISATION', 'POLICE', 'CHAUFFEUR', 'CONCESSION',
       'PARTENAIRE FSF', 'POLICE GAMBIE ', 'TRAITEUR', 'ARTISTE'],
      dtype=object)

In [59]:
groupe = df.groupby("type")["nb"].sum().sort_values(ascending=False)
groupe

type
COMMISSION ORGANISATION                   1124.0
PHOTOGRAPHE                                264.0
JOURNALISTE                                169.0
ARTISTE                                    130.0
SOGIP                                       78.0
EQUIPE NATIONALE DU SENEGAL                 65.0
RTS                                         61.0
JOURNALISTE GAMBIE                          57.0
EQUIPE NATIONALE GAMBIE                     50.0
COMMISSION SECURITE                         47.0
SPONSOR                                     45.0
COMMISSION MEDICALE                         42.0
HOSPITALITE                                 42.0
POLICE                                      38.0
COMMISSION CCATP                            37.0
COMMISSION COMMUNICATION                    32.0
COJOJ                                       28.0
COMITE EXECUTIF                             23.0
COMMISSION PROTOCOLE                        23.0
ADMINISTRATION FEDERALE                     21.0
MINISTERE DE LA JEUNESSE ET DES SPORTS      20.0
COMMISSION MARKETING                        19.0
CONCESSION                                  14.0
OFFICIEL CAF                                13.0
COMMISSION FINANCES                          5.0
SENELEC                                      5.0
TRAITEUR                                     5.0
PRESIDENT LIGUE REGIONALE                    5.0
POLICE GAMBIE                                4.0
COMMISSION ETHIQUE FAIR-PLAY                 4.0
COMMISSION AUDIT                             2.0
PRESIDENT FSF                                1.0
COORDONNATEUR GENERAL                        1.0
PAVOISEMENT                                  1.0
CHAUFFEUR                                    0.0
COMMISSION MOBILISATION                      0.0
PARTENAIRE FSF                               0.0
Name: nb, dtype: float64

In [64]:
nb_chauffeurs = df["type"].value_counts().get("CHAUFFEUR", 0)
nb_chauffeurs

np.int64(20)

In [65]:
commission_mobilisation = df["type"].value_counts().get("COMMISSION MOBILISATION", 0)
commission_mobilisation

np.int64(8)

In [66]:
partenaire_fsf = df["type"].value_counts().get("PARTENAIRE FSF", 0)
partenaire_fsf

np.int64(1)

In [67]:


# Dictionnaire des types et valeurs à attribuer
rules = {
    "CHAUFFEUR": 20,
    "COMMISSION MOBILISATION": 8,
    "PARTENAIRE FSF": 1
}

# Pour chaque type, on trouve la première ligne et on met la valeur
for t, val in rules.items():
    idx = df.index[df["type"] == t]
    if len(idx) > 0:
        df.loc[idx[0], "nb"] = val

In [68]:
groupe = df.groupby("type")["nb"].sum().sort_values(ascending=False)
groupe

type
COMMISSION ORGANISATION                   1124.0
PHOTOGRAPHE                                264.0
JOURNALISTE                                169.0
ARTISTE                                    130.0
SOGIP                                       78.0
EQUIPE NATIONALE DU SENEGAL                 65.0
RTS                                         61.0
JOURNALISTE GAMBIE                          57.0
EQUIPE NATIONALE GAMBIE                     50.0
COMMISSION SECURITE                         47.0
SPONSOR                                     45.0
COMMISSION MEDICALE                         42.0
HOSPITALITE                                 42.0
POLICE                                      38.0
COMMISSION CCATP                            37.0
COMMISSION COMMUNICATION                    32.0
COJOJ                                       28.0
COMITE EXECUTIF                             23.0
COMMISSION PROTOCOLE                        23.0
ADMINISTRATION FEDERALE                     21.0
CHAUFFEUR                                   20.0
MINISTERE DE LA JEUNESSE ET DES SPORTS      20.0
COMMISSION MARKETING                        19.0
CONCESSION                                  14.0
OFFICIEL CAF                                13.0
COMMISSION MOBILISATION                      8.0
TRAITEUR                                     5.0
SENELEC                                      5.0
COMMISSION FINANCES                          5.0
PRESIDENT LIGUE REGIONALE                    5.0
POLICE GAMBIE                                4.0
COMMISSION ETHIQUE FAIR-PLAY                 4.0
COMMISSION AUDIT                             2.0
COORDONNATEUR GENERAL                        1.0
PAVOISEMENT                                  1.0
PARTENAIRE FSF                               1.0
PRESIDENT FSF                                1.0
Name: nb, dtype: float64

In [69]:
df_sum = df["nb"].sum()
df_sum

np.float64(2504.0)

In [71]:
mask = (df["type"] == "COMMISSION ORGANISATION") & (df["nb"] != 0)
df.loc[mask, "nb"] = 109
df_sum = df["nb"].sum()
df_sum

np.float64(17294.0)

In [72]:
# On met d'abord toutes les lignes de ce type à 0
df.loc[df["type"] == "COMMISSION ORGANISATION", "nb"] = 0

# On récupère l'index de la première occurrence
idx = df.index[df["type"] == "COMMISSION ORGANISATION"]

# Si au moins une ligne existe, on met 109 à la première
if len(idx) > 0:
    df.loc[idx[0], "nb"] = 109
df_sum = df["nb"].sum()
df_sum

np.float64(1489.0)

In [76]:
df.to_csv("badge_clean.csv", index=False, encoding="utf-8")

In [74]:
df_clean = pd.read_csv("badge_clean.csv")
df_clean.head()

      nb             structure         type        date
0  169.0  CHALLENGESPORTS.INFO  JOURNALISTE  2026-03-11
1    0.0                   RTS  JOURNALISTE  2026-03-11
2    0.0                RECORD  JOURNALISTE  2026-03-11
3    0.0        Jolofsport.com  JOURNALISTE  2026-03-11
4    0.0                Taggat  JOURNALISTE  2026-03-11

In [75]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["date"] = df["date"].fillna(pd.to_datetime("2026-03-31"))
df.head()

      nb             structure         type       date
0  169.0  CHALLENGESPORTS.INFO  JOURNALISTE 2026-03-11
1    0.0                   RTS  JOURNALISTE 2026-03-11
2    0.0                RECORD  JOURNALISTE 2026-03-11
3    0.0        Jolofsport.com  JOURNALISTE 2026-03-11
4    0.0                Taggat  JOURNALISTE 2026-03-11